ALTER SESSION SET NLS_LANGUAGE='AMERICAN_AMERICA.US8PC437';
SET DEFINE OFF;
SET SQLBLANKLINES ON;

MERGE INTO HELP_TEXTS T
USING (
      SELECT 'This text displays at the top of the Home/Items to Do page. Note: the end of this text includes a link to the refresh schedule. This text is managed on the page region itself.' AS HELP_TEXT_DESCRIPTION,'<p>Items to do include projects/protocols and related tasks from <a href="#AGREEMENTS#">Agreements-DUA</a>, <a href="#COMS#">COMS</a>, <a href="#SAFETY#">Data Safety</a>, <a href="#IRB#">ESTR</a>, <a href="#GMAS#">GMAS</a>, <a href="#HMSIACUC#">HMS IACUC</a>, statements from <a href="#ECRT#">ecrt</a>, certifications from <a href="#OAIR#">OAIR</a>, and assigned training courses from the <a href="#HTP#">Harvard Training Portal</a>. For more information on how often the information refreshes, <a href="INFO_MODAL">view the refresh schedule details</a>.</p>' AS HELP_TEXT,'TODOME_DESCRIPTION' AS HELP_TEXT_KEY FROM DUAL
      UNION ALL
      SELECT 'Application Description','<p>The Research Administration Portal gives faculty and researchers an overview of their research administration and compliance portfolio. The application includes certain projects and protocols from <a href="#AGREEMENTS#">Agreements-DUA</a>, <a href="#COMS#">COMS</a>, <a href="#SAFETY#">Data Safety</a>, <a href="#IRB#">ESTR</a>, <a href="#GMAS#">GMAS</a>, <a href="#HMSIACUC#">HMS IACUC</a>, and <a href="#OAIR#">OAIR</a>, as well as assigned training courses from the <a href="#HTP#">Harvard Training Portal</a>.&nbsp;</p><p>For more details on what is included in the Portal, please visit the <a href="https://ras.fss.harvard.edu/research-administration-portal">support site</a>.</p>','APP_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'Recent Inactive Projects','<p>Inactive projects/protocols COMS registrations, Data Safety protocols,&nbsp;Data Use Agreements, GMAS projects, HMS IACUC protocols, and IRB protocols that have ended or expired within the last 12 months.</p>','INACTIVE_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'Active projects/protocols','<p>Active projects/protocols include active COMS registrations, Data Safety protocols,&nbsp;Data Use Agreements, GMAS projects, HMS IACUC protocols, and IRB protocols. <i>Items from Agreements, COMS, Data Safety, ESTR-IRB and HMS IACUC that will expire in the next three months and GMAS and ESTR-IRB projects that have passed their end date will show a warning icon next to them.</i></p>','ACTIVE_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'Help text for Related Projects modal page.','<p>Current related projects may include COMS registrations, Data Safety protocols,&nbsp;Data Use Agreements, GMAS projects, HMS IACUC protocols, IRB protocols, and OAIR certifications. This list includes projects that are in process, active, and inactive within the last 12 months.</p>','RELATED_PROJECTS_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'Help text for the Related Projects region that displays IDs for the related projects that have been inactive for more than 12 months and for which details are not available in the Portal.','<p>Additional related projects may include COMS registrations, Data Safety protocols,&nbsp;Data Use Agreements, GMAS projects, HMS IACUC protocols, and IRB protocols that are additionally linked (in some cases are inactive) and OAIR certifications that have been withdrawn. This list displays only the IDs of these projects. For additional details, please check the system where the project was created.</p>','RELATED_PROJECTS_DESCRIPTION_NODETAILS' FROM DUAL
      UNION ALL
      SELECT 'Description of items that appear in the Researcher To Do region on the home page.','<p>Researcher Items To Do are items assigned to researchers you support. They include projects/protocols and related tasks from Agreements-DUA, COMS, Data Safety, ESTR, and GMAS, statements from ecrt, certifications from OAIR, and assigned training courses from the Harvard Training Portal.&nbsp;</p><p><strong>Note</strong>: Clicking on a title link will take you to the project/protocol in the home application. However, your access to the project/protocol is set in the home application, so you may not have access to all the items listed here.</p>','RESEARCHER_TODO_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'Active COMS protocol expiring in the next 3 months.','<p><strong>This COMS registration will expire within the next three months.</strong><br><br>If any of the work described on the project is ongoing, submit a new registration immediately.</p><p>If work described in the project has ended, please request inactivation (NOTE: inactivation can only be requested by the project PI).</p>','COMSExpiring' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment changes requested for PI Designees','<p>Changes or clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSAmendmentChangPIDesignee' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment changes requested for the PI','<p>Changes or clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSAmendmentChangPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment changes requested for Study Staff','<p>Changes or clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSAmendmentChangStudyStaff' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment pre-submission instructions for the PI','<p>An amendment has been created and not yet submitted for review. &nbsp;</p><p>To review and complete the submission:</p><ul><li>Click the submission link</li><li>Review the submission and to check if the necessary items have been completed.</li><li>Once the materials are ready, click Submit Amendment to send the submission for review.</li></ul>','COMSAmendmentPre-SPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment pre-submission instructions for the Lab Contact','<p>A amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSAmendmentPre-SLabContact' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment pre-submission instructions for a PI Designee','<p>A amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSAmendmentPre-SPIDesignee' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment pre-submission instructions for Study Staff','<p>A amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSAmendmentPre-SStudyStaff' FROM DUAL
      UNION ALL
      SELECT 'COMS registration changes requested for lab contact','<p>Changes or clarifications have been requested on this COMS registration.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSNewChangLabContact' FROM DUAL
      UNION ALL
      SELECT 'COMS registration changes requested for PI Designees','<p>Changes or clarifications have been requested on this COMS registration.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSNewChangPIDesignee' FROM DUAL
      UNION ALL
      SELECT 'COMS registration changes requested for the PI','<p>Changes or clarifications have been requested on this COMS registration.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSNewChangPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'Active IRB protocol expiring in the next 3 months.','<p>The IRB approval of this study will expire within the next three months. For details, click the submission link to go to the project workspace.</p><p><strong>Continuation of research activities beyond the period of approval is a violation of federal regulations</strong>.</p><p>If you have not already done so, please submit a continuing review to request continuing approval or study closure. You can submit a continuing review by navigating to the active study and clicking Create Modification / CR.</p>','ESTRExpiring' FROM DUAL
      UNION ALL
      SELECT 'Active Data Safety protocols expiring in the next 3 months','<p>This protocol will expire within the next three months. The <a href="https://vpr.harvard.edu/pages/harvard-research-data-security-policy">Harvard Research Data Security Policy</a> requires that an update for this Data Safety submission be provided.</p><p><strong>A renewal or continuing review for this record is due prior to the expiration date.</strong></p><p style="margin-left:40px;">• If there are no changes to propose and no incidents to report: click the submission link and complete the Renew activity on the left of the workspace; OR</p><p style="margin-left:40px;">• If there are changes to propose, incidents, or other items requiring review by a specialist: click the submission link and "Create Amendment/CR". As part of this process choose at least Continuing Review or Amendment/CR and complete the SmartForm.</p><p>Please see the Safety Submission Guide for detailed&nbsp;instructions on&nbsp;<a href="https://ras.fss.harvard.edu/files/ras/files/safety_submission_guide.pdf#page=28&amp;zoom=100,93,822">Renew or Submitting a Continuing Review</a>.&nbsp;</p>','SAFETYExpiring' FROM DUAL
      UNION ALL
      SELECT 'In Process','<p>Items in process include GMAS requests that are under development or review and COM registrations, Data Safety protocols, Data Use Agreements, HMS IACUC protocols, IRB protocols, and OAIR certifications that are in review by your school or central research administration office.</p>','INPROCESS_DESCRIPTION' FROM DUAL
      UNION ALL
      SELECT 'COMS amendment changes requested for lab contact','<p>Changes or clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSAmendmentChangLabContact' FROM DUAL
      UNION ALL
      SELECT 'RNI action response instructions for the principal investigator/reporter','<p>Actions have been required on this new information report.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Click the letter link near the top of the page on the right side - the letter contains the action requirement details</li><li>Click Submit Changes Action Response to describe all action details, provide any attachments, and to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please see the <a href="https://estrsupport.fss.harvard.edu/files/estr/files/irb_study_submission_guide.pdf">IRB Study Submission Guide</a>.</p>','ESTRReportableNewInformationActioPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'Active Data Use Agreements expiring in the next 3 months.','<p><strong>This agreement will expire within the next three months.</strong><br><br>Prior to the expiration date, click the submission link to see the details and to create an amendment (to extend the agreement), if appropriate. Please update the Smart Form to include any important details about the requested amendment (new end date, additional data users, etc.).<br><br>If terms of the agreement indicated additional requirements at closure (such as destruction of data with a certificate, or results sharing), please visit the appropriate site&nbsp;for suggested next steps:&nbsp;</p><ul><li>Harvard T.H. Chan School of Public Health<br><a href="https://hcsra.sph.harvard.edu/">Sponsored Programs Administration(SPA)</a>&nbsp;</li><li>Harvard Medical and Dental Schools<br><a href="https://researchadmin.hms.harvard.edu/">Office of Research Administration(ORA)</a>&nbsp;</li><li>University Area, all other Harvard schools<br><a href="https://osp.finance.harvard.edu/">Office for Sponsored Programs(OSP)</a>&nbsp;</li></ul>','AGREEMENTSExpiring' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required instructions for other personnel','<p>Changes are required on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialChangOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for other personnel','<p>Modifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialModifOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission instructions for other personnel','<p>An IACUC study has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/b._submitting_a_new_protocol.pdf">Guidance for Submitting a New Study</a>.</p>','HMSIACUCInitialPreSOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for a Co-PI','<p>Clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationClariCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission for amendment instructions for a Co-PI','<p>An IACUC amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/d._submitting_an_amendment.pdf">Guidance for Submitting an Amendment</a>.</p>','HMSIACUCModificationPreSCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for PI','<p>Changes are required on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationChangPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for study coordinator','<p>Clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationClariStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission for amendment instructions for study coordinator','<p>An IACUC amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/d._submitting_an_amendment.pdf">Guidance for Submitting an Amendment</a>.</p>','HMSIACUCModificationPreSStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for key personnel','<p>Changes are required on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationChangKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for other personnel','<p>Changes are required on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationChangOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'COMS registration changes requested for Study Staff','<p>Changes or clarifications have been requested on this COMS registration.</p><p>To view the details of the request and respond with the changes click on the submission link to go to the project workspace.</p>','COMSNewChangStudyStaff' FROM DUAL
      UNION ALL
      SELECT 'COMS registration pre-submission instructions for the Lab Contact','<p>A COMS registration has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSNewPre-SLabContact' FROM DUAL
      UNION ALL
      SELECT 'COMS registration pre-submission instructions for a PI Designee','<p>A COMS registration has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSNewPre-SPIDesignee' FROM DUAL
      UNION ALL
      SELECT 'COMS registration pre-submission instructions for Study Staff','<p>A COMS registration has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator should complete the submission and submit it for review.</p>','COMSNewPre-SStudyStaff' FROM DUAL
      UNION ALL
      SELECT 'COMS registration pre-submission instructions for the PI','<p>An COMS registration has been created and not yet submitted for review. &nbsp;</p><p>To review and complete the submission:</p><ul><li>Click the submission link</li><li>Review the submission and to check if the necessary items have been completed.</li><li>Once the materials are ready, click Submit New Study to send the submission for review.</li></ul>','COMSNewPre-SPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for a Co-PI','<p>Changes are required on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationChangCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for study coordinator','<p>Changes are required on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationChangStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'Active IACUC protocol expiring in the next 3 months.','<p><strong>This IACUC study will expire within the next three months.</strong></p><p>For details, click the submission link to go to the project workspace.<br><strong>Continuation of research activities beyond the period of approval is a violation of federal regulations.</strong></p><p>If you have not already done so, please submit a renewal. For more information, reference: <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/c._submitting_a_three-year_renewal.pdf">Submitting a Three-Year Renewal</a>, or <a href="ttps://iacuc.hms.harvard.edu/files/hma-iacuc/files/e._submitting_an_annual_renewal.pdf">Submitting a One-Year Renewal (for projects supported by the DOD)</a></p>','HMSIACUCExpiring' FROM DUAL
      UNION ALL
      SELECT 'Active IRB protocols that have passed their expiration date.','<p>The IRB approval of this study may have expired. For details, click the submission link to go to the project workspace.</p><p style="margin-left:0px;">Required updates to the Harvard IRB include:</p><ul><li>Updates to the approved project:&nbsp;update the approved project by completing steps to “Create site modification/Update study details” (on the left side of the workspace).</li><li>Continuing review:&nbsp;report on continuing review by completing the "Report Continuing Review Data" (on the left side of the workspace). Note that this activity is only visible to the Harvard Principal Investigator.</li><li>Closure of the study with Harvard:&nbsp;request closure completing the "Report Continuing Review Data" activity (on the left side of the workspace). Note that this activity is only visible to the Harvard Principal Investigator.</li><li>Any Reports of New Information:&nbsp;complete steps to “Report New Information” (on the left side of the workspace). Reporting details:<ul><li><a href="https://irb.harvard.edu/IRB/sd/Doc/0/27OCM2QETKU4TESR3GMPVGKSC7/HRP-103-HUA%20Investigator%20Manual.pdf">Harvard University Area Investigator Manual</a></li><li><a href="https://irb.harvard.edu/IRB/sd/Doc/0/488V4CVOPCAKN72LEMSAOG9S0F/HRP-103-HLC%20Investigator%20Manual.pdf">Harvard Longwood Campus&nbsp;Investigator Manual</a></li></ul></li></ul>','ESTRExpired' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required instructions for PI','<p>Changes are required on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialChangPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for PI','<p>Clarifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialClariPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission instructions for a Co-PI','<p>An IACUC study has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/b._submitting_a_new_protocol.pdf">Guidance for Submitting a New Study</a>.</p>','HMSIACUCInitialPreSCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for a Co-PI','<p>Clarifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialClariCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for a Co-PI','<p>Modifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialModifCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required instructions for study coordinator','<p>Changes are required on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialChangStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for study coordinator','<p>Clarifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialClariStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission instructions for study coordinator','<p>An IACUC study has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/b._submitting_a_new_protocol.pdf">Guidance for Submitting a New Study</a>.</p>','HMSIACUCInitialPreSStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required instructions for key personnel','<p>Changes are required on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialChangKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for key personnel','<p>Modifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialModifKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for study coordinator','<p>Modifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialModifStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission instructions for key personnel','<p>An IACUC study has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/b._submitting_a_new_protocol.pdf">Guidance for Submitting a New Study</a>.</p>','HMSIACUCInitialPreSKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission instructions for PI','<p>An IACUC study has been created and not yet submitted for review.</p><p>To review and complete the submission:</p><ul><li>Click the submission link</li><li>Review the submission and to check if the necessary items have been completed.</li><li>Once the materials are ready, click Submit Study to send the submission for review.</li></ul><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/b._submitting_a_new_protocol.pdf">Guidance for Submitting a New Study</a>.</p>','HMSIACUCInitialPreSPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for key personnel','<p>Clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationClariKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC modifications requested for amendment instructions for a Co-PI','<p>Modifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationModifCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC modifications requested for amendment instructions for key personnel','<p>Modifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationModifKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC modifications requested for amendment instructions for PI','<p>Modifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationModifStudyCoordinator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission for amendment instructions for key personnel','<p>An IACUC amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/d._submitting_an_amendment.pdf">Guidance for Submitting an Amendment</a>.</p>','HMSIACUCModificationPreSKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission for amendment instructions for other personnel','<p>An IACUC amendment has been created and not yet submitted for review. &nbsp;</p><p>The Principal Investigator or their Proxy should complete the submission and submit it for review.</p><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/d._submitting_an_amendment.pdf">Guidance for Submitting an Amendment</a>.</p>','HMSIACUCModificationPreSOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for other personnel','<p>Clarifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialClariOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for other personnel','<p>Clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationClariOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required for amendment instructions for PI','<p>Clarifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationClariPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC modifications requested for amendment instructions for other personnel','<p>Modifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationModifOtherPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC modifications requested for amendment instructions for PI','<p>Modifications have been requested on this amendment.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCModificationModifPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC changes required instructions for a Co-PI','<p>Changes are required on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialChangCO-PI' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for key personnel','<p>Clarifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialClariKeyPersonnel' FROM DUAL
      UNION ALL
      SELECT 'IACUC clarifications requested instructions for PI','<p>Modifications have been requested on this study.</p><p>To view the details of the request and respond with the changes:&nbsp;</p><ul><li>Click on the submission link</li><li>Locate the details of the changes, in the Reviewer Notes or History tabs, and read the change details</li><li>Edit the SmartForm to incorporate or respond to changes as needed</li><li>Click Submit Changes to return the submission to the Reviewer</li><li>Click OK</li></ul><p>For more information, please refernce the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/g._responding_to_requests_for_changes.pdf">Guidance for Responding to Request for Changes</a>.</p>','HMSIACUCInitialModifPrincipalInvestigator' FROM DUAL
      UNION ALL
      SELECT 'IACUC pre submission for amendment instructions for PI','<p>An IACUC amendment has been created and not yet submitted for review.</p><p>To review and complete the submission:</p><ul><li>Click the submission link</li><li>Review the submission and to check if the necessary items have been completed.</li><li>Once the materials are ready, click Submit Amendment to send the submission for review.</li></ul><p>For more information, please reference the <a href="https://iacuc.hms.harvard.edu/files/hma-iacuc/files/d._submitting_an_amendment.pdf">Guidance for Submitting an Amendment</a>.</p>','HMSIACUCModificationPreSPrincipalInvestigator' FROM DUAL
) S
ON (T.HELP_TEXT_KEY = S.HELP_TEXT_KEY)
WHEN MATCHED THEN
      UPDATE SET T.HELP_TEXT_DESCRIPTION = S.HELP_TEXT_DESCRIPTION, T.HELP_TEXT = S.HELP_TEXT
WHEN NOT MATCHED THEN
      INSERT (T.HELP_TEXT_ID,T.HELP_TEXT_DESCRIPTION,T.HELP_TEXT,T.HELP_TEXT_KEY) VALUES (HELP_TEXT_SEQ.NEXTVAL,S.HELP_TEXT_DESCRIPTION,S.HELP_TEXT,S.HELP_TEXT_KEY);

COMMIT;
